apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080  # 30000-32767 aralığında bir değer olmalı
  selector:
    app: guestbook-ui
